DROP DATABASE IF EXISTS dream_shop;
CREATE DATABASE IF NOT EXISTS dream_shop CHARACTER SET utf8;
DROP USER dream_worker;
CREATE USER dream_worker IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON dream_shop.* TO 'dream_worker'@'%';